### ISSUE TITLE
Fragments displays wrong arraylists when switched between tabs

### ISSUE THREAD

**Issue by aliusa** [pizza/MaterialTabs#11]
So, I have school timetable with 1 Tab activity with 1 fragment (5 tabs) which displays listview, populated with ArrayList rows through custom Adapter.
Problem occurs when switching content through Tabs. If I scroll out of screen (un-cache), make it offscreen and then scroll back to that Tab, I get correct ArrayList.

If needed, can provide code.

**Comment by pizza** [comment]
Sorry this unfortunately has nothing to do with this library but more with the ViewPager and its FragmentStatePagerAdapter or FragmentPagerAdapter. You might want to check the sample code.

Also, if the fragment in each page of the ViewPager gets "un-cached" as you say, you might want to check this: http://developer.android.com/reference/android/support/v4/view/ViewPager.html#setOffscreenPageLimit(int)
