### ISSUE TITLE
CustomTabProvider Only works with Activities & not with Fragment

### ISSUE THREAD

**Issue by vj-1023** [pizza/MaterialTabs#14]
Implementing CustomTabViewProvider with the adapter works fine with Activities but throws null pointer exception when the tabs are used within the fragment.

Have you checked it ?

**Comment by vj-1023** [comment]
@pizza Please Update on this !

**Comment by pizza** [comment]
@vj-1023 Can you post the LogCat logs related to the null pointer exception?

**Comment by vj-1023** [comment]
@pizza 
Hello Sir,
The error got resolved.
It was a minor mistake.
Sorry for the inconvenience & thank you for the reply.
