### ISSUE TITLE
customizing fonts

### ISSUE THREAD

**Issue by mariem16** [pizza/MaterialTabs#16]
how can we customize the fonts used in this library ??

**Comment by pizza** [comment]
@mariem16 If you would like to use a custom font in the tabs' title text, you can do so in your Java code by adding the last two lines just after binding the tabs to the ViewPager:

``` java
 // Initialize the ViewPager and set an adapter
 ViewPager pager = (ViewPager) findViewById(R.id.pager);
 pager.setAdapter(new SamplePagerAdapter(getSupportFragmentManager()));

 // Bind the tabs to the ViewPager
 MaterialTabs tabs = (MaterialTabs) findViewById(R.id.tabs);
 tabs.setViewPager(pager);

 // Set custom font/typeface to text in tabs' title
 Typeface typeface = Typeface.createFromAsset(getAssets(), "fonts/Roboto-Thin.ttf");
 tabs.setTypeface(typeface, Typeface.BOLD);
```

For this to work, make sure to add your font file (in this case, `Roboto-Thin.ttf`) in the `fonts` folder under `assets`.
