### ISSUE TITLE
All caps in lollipop by default. setAllCaps and app:mtTextAllCaps don't work.

### ISSUE THREAD

**Issue by BlitzKraig** [pizza/MaterialTabs#17]
Can't remove all-caps from the tab titles in Lollipop.

Tried using app:mtTextAllCaps, tabs.setAllCaps(false) and even;

```
TextView tab_title = (TextView) tabs.findViewById(io.karim.materialtabs.R.id.mt_tab_title);
tab_title.setAllCaps(false);
```

with no luck.

**Comment by pizza** [comment]
Hi @BlitzKraig, I just tested the library on Lollipop to try to reproduce what you're having, and I can't. The library works as expected.

If you set `tabs.setAllCaps(false)`, the text should not be all caps anymore. Of course, make sure that the titles you entered aren't hardcoded as all-caps.

While the library works as expected, you made me realize that the titles are hardcoded as all-caps in the sample app and so disabling the "Text All Caps" parameter in the sample app doesn't make any difference, so I'm going to fix that right away. Thanks for that!

Let me know if this still doesn't work for you.

**Comment by BlitzKraig** [comment]
Yup, already changed my titles before I hit this issue. The weird thing is, after changing the fragments the first tab title is now in the correct case, while my other two are all caps :confused: 

Maybe I'm doing something daft. If I come across anything I'll be sure to reply here. Thanks.

**Comment by pizza** [comment]
That's weird indeed. Let me know if you come across anything related to this issue, thanks!

**Comment by BlitzKraig** [comment]
So in my activity's onCreate, I'm doing this:

```
// Initialize the ViewPager and set an adapter
        ViewPager pager = (ViewPager) findViewById(R.id.pager);
        pager.setAdapter(new SamplePagerAdapter(getSupportFragmentManager(), 3));

// Bind the tabs to the ViewPager
        MaterialTabs tabs = (MaterialTabs) findViewById(R.id.tabs);
        tabs.setViewPager(pager);

        tabs.setAllCaps(false);
//        TextView tab_title = (TextView) tabs.findViewById(io.karim.materialtabs.R.id.mt_tab_title);
//        tab_title.setAllCaps(false);

        tabs.setTypeface(bold, Typeface.NORMAL);

```

After commenting out the two lines above setTypeFace, the one correct tab is now incorrect again. So it seems `setAllCaps` isn't working for me, but manually grabbing the textview and setting caps is, for the first tab at least. Any ideas? Am I doing this stuff in the wrong place? Is there some way I can grab the second and third tabs and manually set their `setAllCaps`?

**Comment by pizza** [comment]
Try setting all caps before setting the ViewPager:

```
tabs.setAllCaps(false);
tabs.setViewPager(pager);
```

**Comment by BlitzKraig** [comment]
D'oh! Working perfectly.

Thanks for the super quick help, you're a star.

**Comment by pizza** [comment]
@BlitzKraig You're absolutely welcome. Glad I was able to help! :)
