### ISSUE TITLE
Changing the color of the icon set in getCustomTabView when the user changes tab.

### ISSUE THREAD

**Issue by heanzyzabala** [pizza/MaterialTabs#19]
By default, MaterialTabs has a function to change the selected text color.
But in this instance, instead of using text in the tabs, I used getCustomTabView to change it into icon instead.
Now, how can I change the color of the icon when the user changes tabs?

**Comment by pizza** [comment]
@zheanzy16 Good point, there is no easy developer-friendly way of doing this currently with the library as it is.

I'll try to add this to the library whenever I find free time to do so, but what would be even better is if you could fork the library, implement it yourself and contribute back (if you'd like to of course!)

**Comment by pizza** [comment]
@zheanzy16 Nevermind, I ended up doing it myself. I'll upload a new version of the library later tonight. Thanks for reporting this issue!

**Comment by pizza** [comment]
@zheanzy16 A new version of the library (2.0.5) has been released. Check it out and let me know what you think!
