### ISSUE TITLE
Sometimes the tab tile is not showing up correctly

### ISSUE THREAD

**Issue by dcgavril** [pizza/MaterialTabs#2]
I've tried the demo app and I've found an issue that prevents me from using the library(for the moment). 

The tab tile for "item two" it's partially shown, even when it's selected. On the phone(nexus 5) it's even worse, because it's showing only "two" instead of the full title "item two". 

This can be also seen in the demo gif
 ![sample](https://camo.githubusercontent.com/0f745581482d02e7bd5ad44c8db55ec0ee7ca395/687474703a2f2f696d6775722e636f6d2f664e386565746d2e676966)

I understand that the margins can show a glimpse of what's next, but we need to have at least the activated one that will show the full title text, in order to know the current tab.

**Comment by pizza** [comment]
Very valid issue. I'll try to fix it asap, and get back to you.

Meanwhile, if you're interested, you can always contribute and create a pull request, but this has to be fixed in all cases, so I'll do it very soon.

Thanks!

**Comment by pizza** [comment]
Thanks @dcgavril for reporting this issue! I just fixed it and updated the library version to 2.0.2

I also submitted a new sample APK to the Play Store that should be available in the next couple of hours.

I'll update the GIF soon too :-)

**Comment by dcgavril** [comment]
@pizza Thanks, I'll try it out today.
