### ISSUE TITLE
how to implement a tab bar at the buttom to launch certain avtivity

### ISSUE THREAD

**Issue by yousofkakhki** [pizza/MaterialTabs#21]
hi i have tab bar and a view pager, i add another tab bar at the bottom and didnt connect the one and only viewpager to it since the first tab bar is using it and the second tab bar will take control of that and that is not my intention,i want to implement another tab bar at the bottom just to launch activities. can you tell me how to implement it via your library
thanks in advance

**Comment by heanzyzabala** [comment]
it is helpful to rephrase the context to understand the problem much faster :)

**Comment by pizza** [comment]
@yousofkakhki This is unfortunately not possible with the library as it is right now. Sorry!
