### ISSUE TITLE
Failed to resolve MaterialTabs

### ISSUE THREAD

**Issue by throbi** [pizza/MaterialTabs#22]
Hi!

The demo looked impressive, I wanted to give it a try, but I got the following Gradle error: 

Failed to resolve: com.github.pizza:MaterialTabs:2.0.3

As other projects from jitpack.io compile successfully I think that it must be an issue with MaterialTabs.

Thanks,
Robert

**Comment by pizza** [comment]
Hi @throbi, thanks! Just use `compile 'io.karim:materialtabs:2.0.5'` instead and it should all work fine.
