### ISSUE TITLE
I want to implement the following view

### ISSUE THREAD

**Issue by monowar1993** [pizza/MaterialTabs#23]
I want to achieve the following view by reducing the width of the indicator or of the individual tabs. Please help me out. 
![tabs](https://cloud.githubusercontent.com/assets/13250644/17093642/459c1e36-526c-11e6-9b49-69cc91ccdfb6.png)

**Comment by pizza** [comment]
@monowar1993 This is unfortunately not possible with the library as it is right now. Sorry!
