### ISSUE TITLE
How to resize the icons.

### ISSUE THREAD

**Issue by monowar1993** [pizza/MaterialTabs#24]
@Override
        public View getCustomTabView(ViewGroup parent, int position) {
            ImageView imageView = new ImageView(MainActivity.this);
            imageView.setImageResource(UNSELECTED_ICONS[position]);
            return imageView;
        }

```
    @Override
    public void onCustomTabViewSelected(View view, int position, boolean alreadySelected) {
        Log.i(TAG, "custom tab view selected with position = " + position);
        if (view instanceof ImageView) {
            ((ImageView) view).setImageResource(SELECTED_ICONS[position]);
        }
    }

    @Override
    public void onCustomTabViewUnselected(View view, int position, boolean alreadyUnselected) {
        Log.i(TAG, "custom tab view unselected with position = " + position);
        if (view instanceof ImageView) {
            ((ImageView) view).setImageResource(UNSELECTED_ICONS[position]);
        }
```

}

used this implements. But icon size are to big. Is there any way to set width and height of icon

**Comment by lazymug** [comment]
You can inflate a layout that contains an ImageView

```
<ImageView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/iv_icon"
    android:layout_width="24dp" android:layout_height="24dp"
    android:padding="8dp"/>
```

Notice that you can change width and height and nothing will change...but if you add a PADDING, you will see the icon size changes.
