### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by desugar-64** [pizza/MaterialTabs#5]
Hi, your MaterialTabs a good library. But it will be very nice if you implement next feature. When user scrolling tabs layout, during scroll viewpager must to be scrolled with the tabs and the tab's indicator will update its state too. Anyway, thank you.

**Comment by pizza** [comment]
Hi @sergeyfitis, my goal is to create a library that is a 100% MaterialDesign-compliant.

While your feature request doesn't sound bad at all, I don't plan on adding it to the library anytime soon, sorry!
