### ISSUE TITLE
Is it possible to load custom view in tab?

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [pizza/MaterialTabs#8]

**Comment by pizza** [comment]
Yes, it is possible.

Take a look at this file: https://github.com/pizza/MaterialTabs/blob/master/sample/src/io/karim/materialtabs/sample/MainActivity.java#L149

1 - Make sure that your FragmentPagerAdapter implements `MaterialTabs.CustomTabProvider`
2 - Implement `getCustomTabView(ViewGroup parent, int position)`

In the following example, I am creating a simple custom View which is only an ImageView:

``` java
@Override
public View getCustomTabView(ViewGroup parent, int position) {
        ImageView imageView = new ImageView(MainActivity.this);
        imageView.setImageDrawable(MainActivity.this.getResources().getDrawable(ICONS[position]));
        return imageView;
}
```

**Comment by Morteza-Rastgoo** [comment]
oh... nice!
Thank you!
Please add this in readme to be used by others.
